name: Test

on:
  push:
    branches:
      - master

jobs:
  test_1:
    name: 'Build with node, audit & build'
    uses: infinum/js-pipeline/build.yml@master
    with:
      node_version: '16'
      ci_steps: 'audit build'